### ISSUE TITLE
The ground truth of signed distance is sampled from each shape not the template?

### ISSUE THREAD

**Issue by huilinyang** [Siwensun/Neural_Diffeomorphic_Flow--NDF#3]
Hello, 

I really appreciate the excellent and inspiring work you presented. After reading the paper and codes, I have some questions:

1. How is the ground truth of signed distance sampled? Is it sampled from each shape, not the template? If so, how to ensure the single signed distance function can learn the representation of the template among a class of shapes?

2. I am confused about how to involve t in the ODEFunc, could you please explain a little bit more about it?

3. You clamped the predicted signed distance to [-0.1, 0.1], why should do this kind of clamp?

Thank you very much.

**Comment by Siwensun** [comment]
Thanks for your interest.

1. The ground truth are sampled in the same way as DeepSDF, from each shape. The template are learned together with the shape representation. Displacement regularization as along as diffeomorphic restriction enforce the learned template respect the shared topology and looks similar to each shape within a class;

2. If you want to involve t in the ODEFunc, the easiest way to to add multiple mlp layers to encode t values and then concatenate the encoded t with the state features. Here is a more advanced example. (https://github.com/rtqichen/torchdiffeq/blob/master/examples/cnf.py)

3. It is an empirical setting by DeepSDF. Since we only cares about the surface reconstruction results, only the near surface values are highly related so that more points are sampled near surface as well. On the other hand, it might be easier for a neural network to fit functions within bounded range.
